### ISSUE TITLE
Adding Visualizations to Simulation?

### ISSUE THREAD

**Issue by daylanc** [NVIDIA-AI-IOT/redtail#114]
I've completed the initial simulation portion of this project and was able to use the provided test images to get the drone to move in a circle. I was wondering if were possible to show the image/camera feed in the simulation as well. Something similar to this:

https://discuss.ardupilot.org/t/gsoc-2018-complex-autonomous-tasks-onboard-a-uav-using-a-monocular-camera-nvidia-redtail/31933

Is this something that could easily be added to the docker image/container from this redtail project?

**Comment by somtooo** [comment]
Bro please contact me chukwurahb@gmail.com im having troubles getting nvidia-docker v1 to run
