### ISSUE TITLE
Problem with connecting to Nvidia shield controller via bluetooth on Ubuntu

### ISSUE THREAD

**Issue by chao92** [NVIDIA-AI-IOT/redtail#116]

**Comment by chao92** [comment]
![image](https://user-images.githubusercontent.com/10903038/53930000-55f49180-4055-11e9-922a-105308d2bf2d.png)
Does anyone know how to connect the Nvidia joystick to the Ubuntu Via Bluetooth?

**Comment by chao92** [comment]
I tried to use Blueman, it still does not work.
![image](https://user-images.githubusercontent.com/10903038/53931721-f483f100-405b-11e9-89e6-7d50cdc81e1b.png)

**Comment by Alexey-Kamenev** [comment]
We did not have any problems connecting our Shield controllers on Ubuntu 16.04.
Here is what I see now on my Ubuntu 18.04:
```
[NEW] Device 00:04:4B:77:F1:6C NVIDIA Controller v01.04
[CHG] Device 00:04:4B:77:F1:6C Connected: yes
[NVIDIA Controller v01.04]#
```
Try connecting the controller using USB cable and see if it works.

**Comment by chao92** [comment]
Thank you so much for your prompt response. I just updated my system from 16.04 to 18.04. It could be able to connect right now. but it will automatically disconnect. Did you have ever meet this problem?
![screenshot from 2019-03-07 19-31-42](https://user-images.githubusercontent.com/10903038/54001196-0b841b00-4110-11e9-8459-4b64661bd315.png)
