### ISSUE TITLE
internal_utils.h(64): error: identifier "PluginFormat" is undefined

### ISSUE THREAD

**Issue by Z-Jeff** [NVIDIA-AI-IOT/redtail#124]
when I use "sudo make " , it occur an error like "internal_utils.h(64): error: identifier "PluginFormat" is undefined" .
how can I fix this ?

**Comment by Alexey-Kamenev** [comment]
Which version of TensorRT are you using? StereoDNN was tested with TRT 3.0 and 4.0. We haven't tested it with later versions of TRT so it may not work.

**Comment by Z-Jeff** [comment]
I use Jetpack-3.2 so the version of TensorRT is  3.0.4-1 .

**Comment by Z-Jeff** [comment]
I have known the reason.
TensorRT-4.0 has the definition of  "PluginFormat" while TensorRT-3.0 hasn't.
So I use Jetpack-3.3 to reflash my Jetson tx2 with TensorRT-4.0 , then the error disappears !
