### ISSUE TITLE
any hint whether can bu run on Jetpack 4.2?

### ISSUE THREAD

**Issue by vxgu86** [NVIDIA-AI-IOT/redtail#126]
I could not even run jetson_ros_install.sh, it stuck somewhere, should it only can be used in Jetpack  3.2?

**Comment by mtbsteve** [comment]
that script tries to install ros kinetic which is not supported on Ubuntu 18.04.
You may try to install ros-melodic instead.
Likely you need Ubuntu 16.4 along with JP 3.3 for Redtail.

**Comment by vxgu86** [comment]
for the tx1 or tx2,they tested on :
JetPack 3.2 which contains CUDA 9.0 and TensorRT 3.0.
JetPack 3.3 which contains CUDA 9.0 and TensorRT 4.0.

for Nano, the JetPack 4.2  contains:
TensorRT 5.0.6.3
CUDA 10.166
cuDNN 7.3.1.28

these products should also go with lower version of TersorRT and CUDA, right?
I am trying on this.

**Comment by mtbsteve** [comment]
I got it running with ros-melodic on Ubuntu 18.04 and Jetpack 4.2.2
Here is the link to my github:
https://github.com/mtbsteve/redtail/blob/master/ros/scripts/ardupilot_jetson_JP42_ros_install.sh
Note it’s WIP and frequently updated

**Comment by vxgu86** [comment]
thanks @mtbsteve ,did you test it all with the launches in simu and real drone?

**Comment by mtbsteve** [comment]
@vxgu86 I am currently only working with real drone along with the stereo_dnn_ros and strereo_dnn_ros_viz packages. I have not touched yet the simulation. 
Test cases are a mixed bag. Most of them run well with the exception of resnet18 (NVsmall and resnet18-2d run well). Also, I was not able to get gscam working. But since I use the ZED-ROS wrapper I think I will not need gscam.

**Comment by vxgu86** [comment]
thanks, I will try it on my nano.
by the way, gscam not working due to ubuntu version , 18.04 not 16.04?

**Comment by vxgu86** [comment]
get gscam work on 18.04, right now trying to replace caffe_ros with other node that support 18.04. 
I think will be a good start to fork redtail to 18.04
