### ISSUE TITLE
Cmake Error - ROS Kinetic Angles

### ISSUE THREAD

**Issue by dexterjames** [NVIDIA-AI-IOT/redtail#137]
@Alexey-Kamenev 

Hi Alexey,
I'm receiving some errors when running the `jetson_ros_install.sh` script.  See screenshot below. Any suggestions how to resolve this problem? 

![Angles](https://user-images.githubusercontent.com/53290393/65132188-11788400-d9f0-11e9-99ab-b46329b42f9f.png)

**Comment by mtbsteve** [comment]
have you angles installed? 
```
cd $HOME
sudo apt-get install -y ros-kinetic-angles

```

**Comment by dexterjames** [comment]
Thank you @mtbsteve. Solved using the following commands:

`sudo apt-get upgrade -y ros-kinetic-angles`
